name: CI - Backend

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Setup Node.js for ${{ matrix.project }}
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ${{ matrix.project }}/package-lock.json
          package-manager-cache: true

      - name: Install dependencies for ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: |
          if [[ "$GITHUB_REF_NAME" == "main" || "$GITHUB_REF_NAME" == "integ" ]]; then
            npm ci
          else
            npm install
          fi

      - name: Format check for ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: npm run format

      - name: Build ${{ matrix.project }}
        working-directory: ./${{ matrix.project }}
        run: npm run build
